import {chromium} from '@playwright/test';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4199','--strictPort'],{stdio:'pipe',windowsHide:true});let browser;
try{
 await new Promise(r=>server.stdout.on('data',d=>{if(d.toString().includes('4199'))r()}));browser=await chromium.launch({channel:'msedge',headless:true});
 for(const [width,height] of [[1440,748],[320,568],[844,390]]){
  const context=await browser.newContext({viewport:{width,height},hasTouch:true});const p=await context.newPage();p.setDefaultTimeout(7000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const breaks=[];const click=async name=>{await p.getByRole('button',{name,exact:true}).click();const pause=p.locator('[data-meal-break]');if(await pause.count()){const id=await pause.getAttribute('data-meal-break');if(id==='intro'){await p.getByRole('heading',{name:"We're going to eat and play together now.",exact:true}).waitFor();await p.getByRole('button',{name:"Let's eat and play",exact:true}).click()}else{breaks.push(Number(id));assert.equal(await p.locator('[data-kitchen-stage]').count(),0);const keep=p.getByRole('button',{name:'Keep cooking',exact:true});assert.equal(await keep.isEnabled(),true);const box=await keep.boundingBox();assert.ok(box.y+box.height<=height);if(id==='0'){await p.getByRole('heading',{name:'Chew 5 times, slowly.',exact:true}).waitFor();await p.screenshot({path:`images/kitchen-meal-break-${width}.png`})}await keep.click()}}};const stage=()=>p.locator('[data-kitchen-stage]').getAttribute('data-kitchen-stage');
  async function drag(from,to,touch=false){const a=await p.getByRole('button',{name:from,exact:true}).boundingBox(),b=await p.getByRole('button',{name:to,exact:true}).boundingBox();const x=a.x+a.width/2,y=a.y+a.height/2,tx=b.x+b.width/2,ty=b.y+b.height/2;
   if(touch){const c=await context.newCDPSession(p);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=10;i++)await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+(tx-x)*i/10,y:y+(ty-y)*i/10}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach()}else{await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(tx,ty,{steps:12});await p.mouse.up()}
  }
  await p.goto('http://127.0.0.1:4199');await click('Turn sound off');assert.equal(await p.locator('.location:disabled').count(),0);await p.screenshot({path:`images/kitchen-home-${width}.png`});assert.deepEqual(await p.locator('.location').evaluateAll(buttons=>buttons.filter(el=>{const r=(el.querySelector('.location-label')||el).getBoundingClientRect();return !el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}).map(el=>el.getAttribute('aria-label'))),[]);await click("Visit Milo's Food Garden");await click('Make Carrot Soup');
  const order=await p.locator('.kitchen-foods button').evaluateAll(bs=>bs.map(b=>b.getAttribute('aria-label')));await click('tomato');assert.equal(await p.getByRole('button',{name:'Wash the carrots',exact:true}).count(),0);for(let i=1;i<=3;i++){await click('carrot '+i);if(i<3)assert.equal(await p.getByRole('button',{name:'Wash the carrots',exact:true}).count(),0)}await click('Wash the carrots');
  await drag('Pick up washing water','Wash carrot 1',width===320);await click('Pick up washing water');await click('Wash carrot 2');await click('Wash carrot 3');await click('Find the pieces');
  await click('potato');assert.equal(await p.getByRole('button',{name:'Fill the pot',exact:true}).count(),0);await click('Carrot pieces');await click('Fill the pot');
  await drag('Pick up carrot piece 1','Put carrot pieces in the pot',true);for(let i=2;i<=3;i++){await click('Pick up carrot piece '+i);await click('Put carrot pieces in the pot')}
  await p.screenshot({path:`images/kitchen-pot-${width}.png`});await click('Add water');await click('Pick up water');await click('Add water to pot');await click('Stir the soup');
  const r=await p.locator('.kitchen-stir-pot').boundingBox(),cx=r.x+r.width/2,cy=r.y+r.height/2,rad=r.width*.32;await p.mouse.move(cx+rad,cy);await p.mouse.down();for(let i=1;i<=42;i++){const angle=i/40*2*Math.PI;await p.mouse.move(cx+Math.cos(angle)*rad,cy+Math.sin(angle)*rad)}await p.mouse.up();await p.getByText('1 gentle stirs',{exact:true}).waitFor();await click('Stir once');await click('Stir once');await click('Let it rest');
  assert.equal(await stage(),'6');await p.screenshot({path:`images/kitchen-pause-${width}.png`});assert.equal(await p.getByRole('button',{name:'Keep cooking',exact:true}).isEnabled(),true);if(width===1440){await p.waitForTimeout(12500);await p.getByRole('heading',{name:/^Ready\?.*keep cooking!$/}).waitFor();assert.equal(await stage(),'6')}await click('Keep cooking');
  await click('square bowl');assert.equal(await p.getByRole('button',{name:'Serve the soup',exact:true}).count(),0);await click('circle bowl');await click('Serve the soup');await p.getByRole('button',{name:'Pick up soup spoon',exact:true}).focus();await p.keyboard.press('Enter');await p.getByRole('button',{name:'Serve soup in bowl',exact:true}).focus();await p.keyboard.press('Enter');await click('Sit together');assert.equal(await stage(),'9');await click('Back to the garden');await click('Make Carrot Soup');assert.notDeepEqual(await p.locator('.kitchen-foods button').evaluateAll(bs=>bs.map(b=>b.getAttribute('aria-label'))),order);await click('Back to food garden');await click('Back to world');assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight>innerHeight+1||document.documentElement.scrollWidth>innerWidth+1),false);assert.deepEqual(breaks,[0,1,2,3,4,7,8]);assert.deepEqual(errors,[]);await context.close();
 }
 console.log('PASS: 10-stage soup story, gentle retries, three distinct carrots, mouse/touch dragging, circular stirring and tap fallback, optional pause, varied replay and responsive navigation.');
}finally{await browser?.close();server.kill()}
