import {Action} from '../forest/AnimalActivity'
import {ContinueButton} from '../play/ContinueButton'
import {useEffect,useRef,useState} from 'react'
import type {PointerEvent as ReactPointerEvent} from 'react'
import {ArrowLeft,Volume2,VolumeX} from 'lucide-react'
import {Milo} from '../Illustrations'
import {freshShuffle} from '../variation'
import {narrate,stopNarration} from '../narration'
import {FoodArt,KitchenBackdrop} from './KitchenArt'
import type {FoodKind} from './KitchenArt'
import {Carry,MealMoment} from './KitchenShared'
import {RainbowRice} from './RainbowRice'
import './kitchen.css'
const prompts=['Tap 3 carrots.','Tap the water, then each carrot to wash it.','Tap the picture of carrot pieces.','Tap a carrot piece, then the pot. Add all 3.','Tap the water, then the pot.','Move your finger in circles on the pot, or tap Stir once.','Our soup needs a little time. Let’s enjoy our meal together.','Tap the round bowl.','Tap the spoon, then the bowl to serve soup.','What’s on YOUR plate? Tell your grown-up.']
const nextLabels=['Wash the carrots','Find the pieces','Fill the pot','Add water','Stir the soup','Let it rest','Keep cooking','Serve the soup','Sit together']
function makeRecipe(){return{vegetables:freshShuffle('soup-vegetables',['carrot-1','tomato','carrot-2','potato','carrot-3']),pieces:freshShuffle('soup-pieces',['pieces','potato','tomato'] as FoodKind[]),bowls:freshShuffle('soup-bowls',['circle','square','triangle'])}}
function SoupStage({step,sound,onNext,recipe}:{step:number;sound:boolean;onNext:()=>void;recipe:ReturnType<typeof makeRecipe>}){
 const [found,setFound]=useState<string[]>([]),[picked,setPicked]=useState(''),[done,setDone]=useState(false),[hint,setHint]=useState(''),[stirs,setStirs]=useState(0),[rested,setRested]=useState(false),[angle,setAngle]=useState(-Math.PI/2)
 const stirring=useRef(false),lastAngle=useRef<number|null>(null),distance=useRef(0),stirCount=useRef(0)
 const text=hint||(step===6&&rested?'Ready? Let’s keep cooking!':prompts[step])
 useEffect(()=>{if(sound)return narrate(text)},[sound,text])
 useEffect(()=>{if(step!==6)return;const timer=setTimeout(()=>setRested(true),12000);return()=>clearTimeout(timer)},[step])
 function add(id:string,total:number){if(found.includes(id))return;const next=[...found,id];setFound(next);setHint('');if(next.length===total)setDone(true)}
 function drop(target:string,source=picked){if(done)return;if(step===1&&source==='water'&&target.startsWith('wash-'))add(target,3);else if(step===3&&source.startsWith('piece-')&&target==='pot'){add(source,3);setPicked('')}else if(step===4&&source==='water'&&target==='pot')setDone(true);else if(step===8&&source==='spoon'&&target==='bowl')setDone(true);else setHint('Let’s try it over here.')}
 function stir(){if(stirCount.current>=3)return;stirCount.current+=1;setStirs(stirCount.current);if(stirCount.current===3)setDone(true)}
 function stirPoint(e:ReactPointerEvent<HTMLDivElement>){const r=e.currentTarget.getBoundingClientRect();const x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;if(Math.hypot(x,y)<r.width*.12)return;const current=Math.atan2(y,x);setAngle(current);if(lastAngle.current!==null){let delta=current-lastAngle.current;if(delta>Math.PI)delta-=2*Math.PI;if(delta< -Math.PI)delta+=2*Math.PI;distance.current+=Math.abs(delta);if(distance.current>=Math.PI*2){distance.current-=Math.PI*2;stir()}}lastAngle.current=current}
 return <><section className="kitchen-instruction"><h2 aria-live="polite">{text}</h2><button className="replay" aria-label="Hear cooking instruction" onClick={()=>{if(sound)narrate(text)}}><Volume2 size={22}/></button></section><div className={`kitchen-stage ${step===6||step===9?'kitchen-quiet':''}`} data-kitchen-stage={step} data-step-complete={done||undefined}><KitchenBackdrop/>
  <div className="kitchen-worktop">
  {step===0&&<div className="kitchen-foods">{recipe.vegetables.map(id=><button className={`kitchen-food ${found.includes(id)?'kitchen-found':''}`} key={id} disabled={found.includes(id)||done} aria-label={id.startsWith('carrot')?id.replace('-',' '):id} onClick={()=>id.startsWith('carrot')?add(id,3):setHint('Look for the long orange carrots.')}><FoodArt kind={id.startsWith('carrot')?'carrot':id as FoodKind}/></button>)}</div>}
  {step===1&&<><Carry kind="water" label="Pick up washing water" selected={picked==='water'} onPick={()=>setPicked('water')} onDrop={target=>drop(target,'water')}/><div className="kitchen-foods">{[0,1,2].map(i=><button key={i} className={`kitchen-food ${found.includes('wash-'+i)?'kitchen-found':''}`} data-kitchen-drop={'wash-'+i} aria-label={`Wash carrot ${i+1}`} disabled={found.includes('wash-'+i)} onClick={()=>picked?drop('wash-'+i):setHint('Tap the water, then a carrot.')}><FoodArt kind="carrot"/>{found.includes('wash-'+i)&&<span className="kitchen-clean">Clean!</span>}</button>)}</div></>}
  {step===2&&<div className="kitchen-foods">{recipe.pieces.map(kind=><button key={kind} className="kitchen-food" aria-label={kind==='pieces'?'Carrot pieces':kind} disabled={done} onClick={()=>{if(kind==='pieces'){setDone(true);setHint('The carrot pieces are ready.')}else setHint('Find the orange pieces, like our carrots.')}}><FoodArt kind={kind}/></button>)}</div>}
  {step===3&&<><div className="kitchen-foods">{[0,1,2].map(i=>!found.includes('piece-'+i)&&<Carry key={i} kind="piece" label={`Pick up carrot piece ${i+1}`} selected={picked==='piece-'+i} onPick={()=>setPicked('piece-'+i)} onDrop={target=>drop(target,'piece-'+i)}/>)}</div><button className="kitchen-vessel" data-kitchen-drop="pot" aria-label="Put carrot pieces in the pot" onClick={()=>picked?drop('pot'):setHint('Pick up the carrot pieces first.')}><FoodArt kind="pot" contents={found.length>0?'pieces':undefined}/></button></>}
  {step===4&&<><Carry kind="water" label="Pick up water" selected={picked==='water'} onPick={()=>setPicked('water')} onDrop={target=>drop(target,'water')}/><button className="kitchen-vessel" data-kitchen-drop="pot" aria-label="Add water to pot" onClick={()=>picked?drop('pot'):setHint('Pick up the water first.')}><FoodArt kind="pot" contents={done?'water':'pieces'}/></button></>}
  {step===5&&<div className="kitchen-stirring"><div className="kitchen-stir-pot" role="group" aria-label="Stir the soup with a circular movement" onPointerDown={e=>{if(done)return;stirring.current=true;lastAngle.current=null;e.currentTarget.setPointerCapture(e.pointerId);stirPoint(e)}} onPointerMove={e=>{if(stirring.current&&!done)stirPoint(e)}} onPointerUp={()=>{stirring.current=false;lastAngle.current=null}} onPointerCancel={()=>{stirring.current=false;lastAngle.current=null}}><FoodArt kind="pot" filled/><span className="kitchen-spoon" style={{left:`${50+23*Math.cos(angle)}%`,top:`${42+12*Math.sin(angle)}%`}}><FoodArt kind="spoon"/></span></div><Action disabled={done} onClick={()=>{setAngle(a=>a+Math.PI/2);stir()}}>Stir once</Action><p>{stirs} gentle stirs</p></div>}
  {(step===6||step===9)&&<div className="kitchen-table-together"><div className="kitchen-table-milo"><Milo mood="happy"/></div><div className="kitchen-table-bowl"><FoodArt kind="bowl" filled/></div><div className="kitchen-table-spoon"><FoodArt kind="spoon"/></div></div>}
  {step===7&&<div className="kitchen-foods">{recipe.bowls.map(shape=><button key={shape} className="kitchen-food" aria-label={`${shape} bowl`} disabled={done} onClick={()=>shape==='circle'?setDone(true):setHint('Find the round bowl, with no corners.')}><FoodArt kind="bowl" shape={shape}/></button>)}</div>}
  {step===8&&<><Carry kind="spoon" filled label="Pick up soup spoon" selected={picked==='spoon'} onPick={()=>setPicked('spoon')} onDrop={target=>drop(target,'spoon')}/><button className="kitchen-vessel" data-kitchen-drop="bowl" aria-label="Serve soup in bowl" onClick={()=>picked?drop('bowl'):setHint('Pick up the soup spoon first.')}><FoodArt kind="bowl" filled={done}/></button></>}
  </div>
 </div><footer className="kitchen-footer">{step!==6&&step!==9&&<div className="kitchen-companion"><Milo mood={done?'happy':'curious'}/></div>}<div className="kitchen-status" aria-live="polite">{[0,1,3].includes(step)?`${found.length} of 3`:done?'Ready for the next part.':step===6?'Look away and enjoy a moment together.':step===9?'Talk together. There is no hurry.':''}</div>{(done||step===6||step===9)&&<ContinueButton onClick={onNext}>{step===9?'Back to the garden':nextLabels[step]}</ContinueButton>}</footer></>
}
export function KitchenWorld({sound,onSound,onBack}:{sound:boolean;onSound:()=>void;onBack:()=>void}){
 const [rice,setRice]=useState(false)
 const [step,setStep]=useState<number|null>(null),[recipe,setRecipe]=useState(makeRecipe),[mealBreak,setMealBreak]=useState<number|null>(null)
 useEffect(()=>{if(sound&&step===null&&!rice)return narrate('What shall we cook together?')},[sound,step,rice])
 function advance(){stopNarration();if(step===null)return;if([0,1,2,3,4,7,8].includes(step))setMealBreak(step);else setStep(step===9?null:step+1)}
 if(rice)return <RainbowRice sound={sound} onSound={onSound} onBack={()=>{stopNarration();setRice(false)}}/>
 return <main className="kitchen-world"><header className="kitchen-header"><button className="round-button" aria-label={step===null?'Back to world':'Back to food garden'} onClick={()=>{stopNarration();setMealBreak(null);if(step===null)onBack();else setStep(null)}}><ArrowLeft size={21}/></button><div><span>MILO'S FOOD GARDEN</span><h1>{step===null?'Something warm to share':'Carrot Soup'}</h1></div><button className="round-button" aria-label={sound?'Turn sound off':'Turn sound on'} onClick={onSound}>{sound?<Volume2 size={21}/>:<VolumeX size={21}/>}</button></header>{step===null?<><p className="kitchen-welcome">What shall we cook together?</p><div className="kitchen-stage kitchen-recipe kitchen-two-recipes"><KitchenBackdrop/><button className="kitchen-recipe-button" aria-label="Make Carrot Soup" onClick={()=>{setRecipe(makeRecipe());setStep(-1)}}><FoodArt kind="pot" filled/><span>Carrot Soup</span></button><button className="kitchen-recipe-button" aria-label="Make Rainbow Rice" onClick={()=>{stopNarration();setRice(true)}}><FoodArt kind="ricebowl" filled/><span>Rainbow Rice</span></button></div><footer className="kitchen-footer"><div className="kitchen-companion"><Milo mood="curious"/></div><p>A little cooking. A little time together.</p></footer></>:step===-1?<MealMoment intro sound={sound} onContinue={()=>{stopNarration();setStep(0)}}/>:mealBreak!==null?<MealMoment key={mealBreak} afterStep={mealBreak} sound={sound} onContinue={()=>{stopNarration();setStep(mealBreak+1);setMealBreak(null)}}/>:<SoupStage key={step} step={step} recipe={recipe} sound={sound} onNext={advance}/>}</main>
}
