import { freshShuffle } from './variation'
import { narrate, stopNarration } from './narration'
import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Volume2, VolumeX, Home, Sun, Moon, Leaf, X, RotateCcw, BookOpen, Footprints, Settings, Check } from 'lucide-react'
import { Milo, Plant, World } from './Illustrations'
import { PicnicActivity } from './PicnicActivity'
import { HomeWorld } from './home/HomeWorld'
import { ForestWorld } from './forest/ForestWorld'
import { Analytics } from '@vercel/analytics/react'

const extras=['Picnic surprise','Hungry bunnies','Butterfly friends','A sound in the bushes','Play with frog','Tell a little story','Find something','Tidy the cottage','Plant a little seed','A rainy day','Forest hide-and-seek','Remember the story']
const symbols=['🍎','🐇','🦋','🐦','🐸','🗝️','🔴','🧸','🌱','☂️','🍄','📖']
function newActivities() {
 return { order: freshShuffle('activity-order',[0,1,2,3,4,5,6,7,8]), carrots: freshShuffle('bunny-count',[2,3,4])[0], extraBunnies: freshShuffle('bunny-extra',[1,2,3])[0], same: freshShuffle('butterfly-match',[true,false])[0], sound: freshShuffle('animal-sound',[0,1,2])[0], jumps: freshShuffle('movement-count',[2,3,4])[0], movements: freshShuffle('movement-order',[0,1,2]), finds: freshShuffle('find-prompts',['red','blue','round','soft','smaller than your hand']).slice(0,3), props: freshShuffle('story-props',['🗝️','🥚','🌙','🍃','🐚','🎈','🪶','🧺']).slice(0,3), colors: freshShuffle('bridge-colors',['red','blue','yellow','purple']), mushroomSpots: freshShuffle('mushroom-spots',[[18,35],[48,55],[76,25],[31,65],[65,70],[81,60]]).slice(0,3) }
}
type Stats={attempted:string[];completed:string[];hints:number;started:number}
const fresh=():Stats=>({attempted:[],completed:[],hints:0,started:Date.now()})
function saved(){try{const x=JSON.parse(localStorage.getItem('milo-session')||'null');return x&&Array.isArray(x.attempted)&&Array.isArray(x.completed)&&typeof x.started==='number'?x as Stats:fresh()}catch{return fresh()}}
export default function App(){
 const [homeReturn,setHomeReturn]=useState(false)
 const [now,setNow]=useState(Date.now)
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer)},[])
 const [screen,setScreen]=useState('world'),[sound,setSound]=useState(true),[parent,setParent]=useState(false),[stats,setStats]=useState(saved),[message,setMessage]=useState(''),[done,setDone]=useState(false),[step,setStep]=useState(0),[selected,setSelected]=useState(-1),[fixed,setFixed]=useState<number[]>([]),[held,setHeld]=useState(''),[hard,setHard]=useState(false)
 const [variation,setVariation]=useState(newActivities)
 const mix=<T,>(values:T[])=>variation.order.filter(i=>i<values.length).map(i=>values[i])
 const extra=extras.indexOf(screen)
 useEffect(()=>{try{localStorage.setItem('milo-session',JSON.stringify(stats))}catch{/* Optional local persistence. */}},[stats])
 const say=(text:string)=>{if(sound)narrate(text)}
 const go=(name:string)=>{setVariation(newActivities());if(['world','home'].includes(name))setHomeReturn(false);stopNarration();setScreen(name);setStep(0);setSelected(-1);setFixed([]);setHeld('');setMessage('');setDone(false);if(!['world','ending','home'].includes(name))setStats(s=>({...s,attempted:[...new Set([...s.attempted,name])]}))}
 const win=()=>{setDone(true);setMessage('You figured it out!');setStats(s=>({...s,completed:[...new Set([...s.completed,screen])]}))}
 const hint=(text='Hmm… let’s look again.')=>{setMessage(text);say(text);setStats(s=>({...s,hints:s.hints+1}))}
 const next=()=>{setStep(s=>s+1);setMessage('');setFixed([])}
 const choose=(yes:boolean)=>yes?win():hint()
 const item=(symbol:string,label:string,action:()=>void)=><button key={symbol+label} className="object-choice" onClick={action}><span>{symbol}</span><small>{label}</small></button>
 const drag=(symbol:string,value:string)=><button key={value} className={`object-choice ${held===value?'selected':''}`} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',value);setHeld(value)}} onClick={()=>setHeld(value)} aria-label={`Pick up ${symbol}`}><span>{symbol}</span></button>
 const drop=(action:(v:string)=>void)=>({onDragOver:(e:React.DragEvent)=>e.preventDefault(),onDrop:(e:React.DragEvent)=>{e.preventDefault();action(e.dataTransfer.getData('text/plain'));setHeld('')},onClick:()=>{if(held){action(held);setHeld('')}}})
 const chirp=()=>{if(!sound)return;if(variation.sound!==0){say(variation.sound===1?'Ribbit, ribbit':'Woof, woof');return;}const a=new AudioContext();[0,.25,.5].forEach(t=>{const o=a.createOscillator(),g=a.createGain();o.frequency.setValueAtTime(2200,a.currentTime+t);o.frequency.exponentialRampToValueAtTime(3300,a.currentTime+t+.1);g.gain.setValueAtTime(0,a.currentTime+t);g.gain.linearRampToValueAtTime(.1,a.currentTime+t+.02);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+t+.18);o.connect(g);g.connect(a.destination);o.start(a.currentTime+t);o.stop(a.currentTime+t+.2)});setTimeout(()=>void a.close(),1000);if(hard)setTimeout(()=>say('A second sound: rustling leaves'),1200)}
 const title=({plants:'The forest mystery',bridge:'A little way across',nest:'A cosy place to rest',story:'The Story Tree',ending:'A lovely day of discoveries',home:'Milo’s little home'} as Record<string,string>)[screen]||screen
 const prompt=screen==='plants'?'Hmm… why aren’t these plants growing?':screen==='bridge'?(step===0?'Which stone comes next?':'Which flower comes next?'):screen==='nest'?(step===0?'Can you find something soft near you?':'Did it feel soft or hard?'):screen==='story'?['Milo heard scratching behind a little wooden door.','Tiny footprints led toward the kitchen.','Oh! A piece of cheese was missing.','Who do you think took the cheese?','Why do you think so?','A little mouse was sharing it with her family.'][step]:screen==='ending'?'We discovered a lot today.':screen==='home'?'What shall we do together?':[
 "Let's share a little picnic!",fixed.length<variation.carrots?`Share ${variation.carrots} carrots, one per bunny.`:hard?`${variation.carrots+variation.extraBunnies} bunnies, ${variation.carrots} carrots. How many more?`:'How many carrots did we use?','Do these butterflies look the same?',hard?'Which sound came first?':'What did Milo hear?',[`Jump ${variation.jumps} times like a frog!`,'Stretch up tall like a tree.','Freeze like a statue!'][variation.movements[step]],'Can you imagine a story with these?',`Find something ${variation.finds[step]} near you.`,'Put the food and toys in their baskets.',['What happens first?','What happens next?','And then?','What comes last?'][fixed.length],'Rain is coming. What should Milo take?','Can you find three mushrooms?',['What happened first?','What happened next?','What happened last?'][fixed.length]][extra]
 function optionalContent(){switch(extra){
 case 0:return <PicnicActivity key={String(hard)} hard={hard} onInstruction={setMessage} onHint={hint} onComplete={win}/>
 case 1:return <><div className="choices">{Array.from({length:hard?variation.carrots+variation.extraBunnies:variation.carrots},(_,i)=><button className="object-choice" key={i} aria-label={`Feed bunny ${i+1}`} {...drop(()=>{if(!fixed.includes(i)&&fixed.length<variation.carrots)setFixed([...fixed,i])})}><span>🐇</span><small>{fixed.includes(i)?'🥕':'Hungry bunny'}</small></button>)}</div>{fixed.length<variation.carrots?<div className="choices">{drag('🥕','carrot')}<p>Tap a carrot, then a bunny.<br/>Or drag it over.</p></div>:<div className="choices">{mix([1,2,3,4]).map(n=>item(String(n),'',()=>choose(n===(hard?variation.extraBunnies:variation.carrots))))}</div>}</>
 case 2:return <><div className="butterflies"><span>🦋</span><span style={{filter:variation.same?'none':'hue-rotate(80deg)'}}>🦋</span></div><div className="choices">{item('↔','Same',()=>choose(variation.same))}{item('◒','Different',()=>choose(!variation.same))}</div></>
 case 3:return <><button className="sound-orb" onClick={chirp} aria-label="Play animal sound"><Volume2 size={45}/></button><p className="subtle">Tap to listen</p><button className="text-button" onClick={()=>setMessage(["Tweet, tweet! A little chirp.","Ribbit, ribbit! A low croak.","Woof, woof! A friendly bark."][variation.sound])}>Read a sound clue</button><div className="choices">{mix(['🐦','🐸','🐶'].map((v,i)=>[i,v] as const)).map(([i,v])=>item(v,['Bird','Frog','Dog'][i],()=>choose(i===variation.sound)))}</div></>
 case 4:return <><div className={`movement-icon ${step===0?'frog-hop':''}`}>{['🐸','🌳','🗿'][variation.movements[step]]}</div><p>Find a little space around you.</p><button className="primary" onClick={()=>step<2?next():win()}>Done! <Check size={18}/></button></>
 case 5:return <><div className="story-props">{variation.props.join(" ")}</div><p>Tell your story to someone with you, or imagine it quietly. Tap Done when you are finished.</p><button className="primary" onClick={win}>Done telling my story <Check size={18}/></button></>
 case 6:return <><div className="movement-icon">{({red:'🔴',blue:'🔵',round:'⚪',soft:'🧶','smaller than your hand':'🖐️'} as Record<string,string>)[variation.finds[step]]}</div><p>Take your time. Milo will wait here.</p><button className="primary" onClick={()=>step<2?next():win()}>I found it! <Check size={18}/></button></>
 case 7:return <><div className="choices">{mix(['🍎','🧸','🍌','⚽','🥕'].map((v,i)=>[i,v] as const)).map(([i,v])=>!fixed.includes(i)&&drag(v,String(i)))}</div><div className="choices">{mix(['Food','Toys'].map((v,i)=>[i,v] as const)).map(([i,v])=><button key={v} className="basket" {...drop(value=>{const n=Number(value);if((i===0?[0,2,4]:[1,3]).includes(n)){const a=[...new Set([...fixed,n])];setFixed(a);if(a.length===5)win()}else hint('Can we eat it, or play with it?')})}><span>{i===0?'🍎':'🧸'}</span>{v}</button>)}</div><p className="subtle">Drag, or tap an object and its basket.</p></>
 case 8:case 11:{const seq=extra===8?['🌰','💧','🌱','🌻']:['🐾','🚶','🐭'];return <><div className="sequence-slots">{seq.map((v,i)=><div key={v}>{fixed.includes(i)?v:i+1}</div>)}</div><div className="choices">{mix(extra===8?[0,1,2,3]:[0,1,2]).map(i=>!fixed.includes(i)&&item(seq[i],extra===11?['Find footprints','Follow footprints','Find mouse'][i]:'',()=>{if(i===fixed.length){setFixed([...fixed,i]);if(i===seq.length-1)win()}else hint('What needs to happen before that?')}))}</div></>}
 case 9:return <><div className="movement-icon">🌧️</div><div className="choices">{mix(['☂️','🕶️','🍴'].map((v,i)=>[i,v] as const)).map(([i,v])=>item(v,['Umbrella','Sunglasses','Fork'][i],()=>choose(i===0)))}</div></>
 default:return <div className="hidden-scene"><span className="scene-tree">🌳</span><span className="scene-bush">🌿</span>{[0,1,2].map(i=><button key={i} className={`mushroom mushroom-${i} ${fixed.includes(i)?'found':''}`} style={{left:`${variation.mushroomSpots[i][0]}%`,top:`${variation.mushroomSpots[i][1]}%`,right:"auto",bottom:"auto"}} aria-label={`Mushroom ${i+1}`} onClick={()=>{if(!fixed.includes(i)){setFixed([...fixed,i]);if(fixed.length===2)win()}}}>🍄{fixed.includes(i)&&<Check/>}</button>)}<small>{fixed.length} of 3 found</small></div>}}
 if(screen==='forest')return <ForestWorld sound={sound} onSound={()=>{setSound(!sound);stopNarration()}} onWorld={()=>go('world')} onHome={()=>go('home')}/>
 if(screen==='home')return <HomeWorld hard={hard} sound={sound} onSound={()=>{setSound(!sound);stopNarration()}} onWorld={()=>go('world')} onPicnic={()=>{go(extras[0]);setHomeReturn(true)}} onStory={()=>{go('story');setHomeReturn(true)}} onRecord={(name,event)=>setStats(s=>event==='hint'?{...s,hints:s.hints+1}:event==='attempt'?{...s,attempted:[...new Set([...s.attempted,name])]}:{...s,completed:[...new Set([...s.completed,name])]})}/>
 return <main className={`app ${screen==='world'?'map-view':'inside'} ${['story','ending'].includes(screen)?'evening':''} ${(screen==='nest'&&step===0)||[4,6].includes(extra)?'quiet':''}`}><World evening={['story','ending'].includes(screen)}/><header><button className="brand" onClick={()=>go('world')} aria-label="Milo's world"><span className="brand-name">milo<span className="brand-leaf">✦</span></span><span>A LITTLE WORLD OF WONDER</span></button><div className="top-tools">{screen!=='world'&&<button className="round-button" aria-label="Go home" onClick={()=>go('home')}><Home size={21}/></button>}<button className="round-button" aria-label={sound?'Turn sound off':'Turn sound on'} onClick={()=>{setSound(!sound);stopNarration()}}>{sound?<Volume2 size={22}/>:<VolumeX size={22}/>}</button><button className="round-button parent-button" aria-label="Grown-up settings" onClick={()=>setParent(true)}><Settings size={20}/></button></div></header>
 {screen==='world'?<><div className="morning-note"><Sun size={17}/><span>A new day. A little adventure.</span></div><div className="world-title"><span>WELCOME TO</span><h1>Milo’s little world</h1><p>Big discoveries begin with little wonders.</p></div><button className="location home-location" onClick={()=>go('home')} aria-label="Explore Milo's home"><span className="location-label">Milo’s home <Home size={15}/></span></button><button className="location forest-location" onClick={()=>go('forest')} aria-label="Follow the forest path"><span className="path-marker"><Footprints size={24}/></span><span className="location-label">The forest <Leaf size={16}/></span><span className="location-note">A little mystery awaits</span></button><button className="location tree-location" onClick={()=>go('story')} aria-label="Visit the Story Tree"><span className="location-label">Story Tree <BookOpen size={16}/></span></button><div className="welcome-milo"><Milo mood="curious"/></div><section className="welcome-dialogue"><div><span className="eyebrow">MILO</span><h2>Good morning! I’m Milo.</h2><p>Something strange happened in the forest…</p></div><button className="replay" aria-label="Hear Milo" onClick={()=>say('Good morning! I’m Milo. Something strange happened in the forest. Shall we take a look?')}><Volume2 size={21}/></button><button className="primary" onClick={()=>go('forest')}>Let’s take a look <ArrowRight size={19}/></button></section><div className="world-bottom"><span><Leaf size={14}/> A little curiosity goes a long way.</span><span>Made for little explorers</span></div></>:<><div className="adventure-heading"><button className="round-button" aria-label={homeReturn?'Back to house':'Back to world'} onClick={()=>go(homeReturn?'home':'world')}><ArrowLeft size={22}/></button><div><span className="eyebrow">{screen==='story'?'AN EVENING STORY':screen==='home'?'MAKE YOURSELF AT HOME':'A LITTLE ADVENTURE'}</span><h1>{title}</h1></div><Leaf className="chapter-icon"/></div><section className={`activity-panel ${done?'is-success':''}`}><div className="instruction"><h2 aria-live="polite">{message||prompt}</h2><button className="replay" aria-label="Replay instruction" onClick={()=>say(message||prompt)}><Volume2 size={22}/></button></div>
 {screen==='plants'&&<><div className="plants">{mix([0,1,2]).map(i=><button key={i} className={`plant ${selected===i?'selected':''}`} onClick={()=>{setSelected(i);setMessage(i===0?'Damp soil, warm sunshine… and a lovely flower.':fixed.includes(i)?'Look at those happy flowers!':i===1?'The soil is damp. It’s very shady here.':'Warm sunshine… but this soil feels dry.')}}><span className="plant-weather">{i===1&&!fixed.includes(i)?'☁️':'☀️'}</span><Plant bloom={i===0||fixed.includes(i)} dry={i===2&&!fixed.includes(i)}/><span>{['In the sunshine','Under a cloud','A dry little patch'][i]}</span></button>)}</div>{selected>0&&!fixed.includes(selected)&&<><p>What do you think this plant needs?</p><div className="choices">{mix(['💧','☀️','🍎'].map((v,i)=>[i,v] as const)).map(([i,v])=>item(v,['Water','Sunlight','Food'][i],()=>{if((selected===1&&i===1)||(selected===2&&i===0)){setFixed([...fixed,selected]);setMessage('You figured it out! Look at it grow.');if(fixed.length===1)win()}else hint(selected===1?'The soil is damp. What is hiding behind the cloud?':'Look closely at the dry soil.')}))}</div></>}{selected===-1&&<p className="subtle">Tap each plant. What do you notice?</p>}</>}
 {screen==='bridge'&&<><div className="bridge"><div className="stream"/>{Array.from({length:step===0?5:4},(_,i)=>({red:'#bd8d78',yellow:'#dbbd69',blue:'#91b2c0',purple:'#b5a0bf'} as Record<string,string>)[variation.colors[(step===0?0:2)+i%2]]).map((c,i)=><div key={i} className="stone" style={{background:c}}>{step===1?'✿':''}</div>)}<button aria-label="Missing piece" className="stone gap" {...drop(v=>{if(v===variation.colors[step===0?1:2]){if(step===0){next();setMessage('The bridge is whole! Look, a flower path.')}else win()}else hint('Look at how the colors take turns.')})}>?</button></div><div className="choices">{mix(variation.colors).map(c=><button key={c} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',c);setHeld(c)}} onClick={()=>setHeld(c)} className={`choice-stone ${held===c?'selected':''}`} style={{background:({red:'#bd8d78',yellow:'#dbbd69',blue:'#91b2c0',purple:'#b5a0bf'} as Record<string,string>)[c]}} aria-label={`${c} piece`}>{step===1?'✿':''}</button>)}</div><p className="subtle">Drag into the gap, or tap a piece, then the gap.</p></>}
 {screen==='nest'&&<><div className={`nest ${done?'settled':''}`}><span>🐦</span><span>🪹</span></div>{!done&&(step===0?<><p>Find something soft! Milo will wait here.</p><button className="primary" onClick={next}>I found it! <Check size={19}/></button></>:<div className="choices">{mix([0,1]).map(i=>i===0?item('🧶','Soft',win):item('🪨','Hard',()=>{hint('Can you find something cosy and soft?');setStep(0)}))}</div>)}</>}
 {screen==='story'&&<><div className="story-illustration">{['🚪','🐾','🧀','🐾　🧀','🐭','🐭　🧀　🐁'][step]}</div>{step<3?<button className="primary" onClick={next}>Then what happened? <ArrowRight size={19}/></button>:step===3?<div className="choices">{mix(['🐭','🐘','🐟'].map((v,i)=>[i,v] as const)).map(([i,v])=>item(v,['Mouse','Elephant','Fish'][i],()=>{setSelected(i);next()}))}</div>:step===4?<div className="choices reasons">{mix(['🐾','🌊','🐘'].map((v,i)=>[i,v] as const)).map(([i,v])=>item(v,['Tiny footprints','Lives underwater','Very big'][i],()=>{if(i===0&&selected===0){next();setStats(s=>({...s,completed:[...new Set([...s.completed,'story'])]}))}else{hint('Look at the tiny footprints. Who could make them?');setStep(3)}}))}</div>:<><p>“There’s enough for everyone,” smiled Milo.</p><button className="primary" onClick={()=>go(extras[11])}>Remember our story <ArrowRight size={19}/></button><button className="text-button" onClick={()=>go(homeReturn?'home':'ending')}>Walk home with Milo</button></>}</>}
 {extra>=0&&(!done||extra===0)&&optionalContent()}
 {screen==='ending'&&<><div className="bedtime-milo"><Milo mood="sleepy"/></div><div className="recap">{[['plants','🌱','Helped the plants'],['bridge','🪨','Fixed the bridge'],['nest','🐦','Helped the bird'],['story','📖','Solved the mystery']].filter(([id])=>stats.completed.includes(id)).map(([id,icon,label])=><span key={id}>{icon}<small>{label}</small></span>)}</div><h3>See you next adventure.</h3><p className="subtle">Time for a little rest.</p></>}
 {done&&<div className="success-note"><Leaf size={30}/><h3>{screen==='nest'?'A soft nest. A happy little bird.':screen==='bridge'?'A path to somewhere new.':'A little discovery, thanks to you.'}</h3><button className="primary" onClick={()=>go(screen==='plants'?'bridge':screen==='bridge'?'nest':screen==='nest'?'story':homeReturn?'home':extra===11?'ending':'world')}>{extra===11?'Walk home with Milo':'Let’s wander on'} <ArrowRight size={19}/></button></div>}</section>{!['ending','home'].includes(screen)&&<div className="companion"><Milo mood={done?'happy':message?'thinking':'curious'}/><span>We’ll figure it out together.</span></div>}</>}
 {parent&&<div className="modal-backdrop" onClick={()=>setParent(false)}><section className="parent-panel" role="dialog" aria-modal="true" aria-label="Grown-up corner" onClick={e=>e.stopPropagation()}><button className="round-button close" aria-label="Close settings" onClick={()=>setParent(false)}><X/></button><span className="eyebrow">FOR GROWN-UPS</span><h2>A peek at today</h2><p>Play at their pace. There are no scores here.</p><div className="stats"><span><b>{stats.attempted.length}</b>Explored</span><span><b>{stats.completed.length}</b>Discovered</span><span><b>{stats.hints}</b>Gentle hints</span><span><b>{Math.max(0,Math.floor((now-stats.started)/60000))} min</b>Time together</span></div><label className="difficulty"><input type="checkbox" checked={hard} onChange={e=>setHard(e.target.checked)}/> A little more challenge (ages 6–8)</label><h3>Explore a little more</h3><button className="text-button" onClick={()=>{setParent(false);go('plants')}}>Original plant and bridge adventure</button><div className="activity-links">{extras.map((v,i)=><button key={v} onClick={()=>{setParent(false);go(v)}}>{symbols[i]} {v}<ArrowRight size={14}/></button>)}</div><div className="parent-footer"><button className="text-button" onClick={()=>{setParent(false);go('ending')}}>End the day <Moon size={16}/></button><button className="text-button" onClick={()=>{setStats(fresh());try{localStorage.removeItem('milo-home-v1');localStorage.removeItem('milo-forest-world-v1')}catch{}setParent(false);go('world')}}><RotateCcw size={16}/> Restart session</button></div><small>Sound buttons read instructions aloud. Milo does not hear or answer speech. Use touch controls to play; no speaking is required. Session notes stay on this device.</small></section></div>}
 <Analytics />
 </main>
}
